/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nineclassdit102;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ipae
 */
public class frmCreateFile extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmCreateFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLocation = new javax.swing.JTextField();
        lbCreateFile = new javax.swing.JButton();
        lbDeleteFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLocation.setColumns(10);

        lbCreateFile.setText("Create File");
        lbCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbCreateFileActionPerformed(evt);
            }
        });

        lbDeleteFile.setText("Delete File");
        lbDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbDeleteFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDeleteFile)
                    .addComponent(lbCreateFile))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCreateFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDeleteFile)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCreateFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int returnValue = fc.showSaveDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            txtLocation.setText(file.getAbsolutePath());
        try {
            File myObj = new File(txtLocation.getText());
        if (myObj.createNewFile()) {
            JOptionPane.showMessageDialog(rootPane, "File created: " + myObj.getName());
        } else {
            JOptionPane.showMessageDialog(rootPane, "File already exists.");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred.");
            e.printStackTrace();
        }
}
else
JOptionPane.showMessageDialog(rootPane, "Create File Command cancelled by user");
    }//GEN-LAST:event_lbCreateFileActionPerformed

    private void lbDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbDeleteFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        int value = chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String filename= f.getAbsolutePath();

        File Obj = new File(filename);

        // Deleting File
        if (Obj.delete()) {
            JOptionPane.showMessageDialog(null,"The deleted file is : " + Obj.getName());
        }
        else {
            JOptionPane.showMessageDialog(null,"Failed in deleting the file.");
}
    }//GEN-LAST:event_lbDeleteFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreateFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreateFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreateFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreateFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCreateFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lbCreateFile;
    private javax.swing.JButton lbDeleteFile;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
