/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package excerciseoperationcal;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ipae
 */
public class randomSumOutput2 extends javax.swing.JFrame {

    /**
     * Creates new form randomSumOutput2
     */
    public randomSumOutput2() {
        initComponents();
    }

    Random rnd = new Random();
    
    int randomNum1, randomNum2, randomNum3,fact1ToInt,fact2ToInt,fact3ToInt,realAnswer;
    
    String[] compliments = {
            "Excellent", 
            "Amazing", 
            "Outstanding", 
            "Fantastic", 
            "Incredible", 
            "Awesome", 
            "Brilliant", 
            "Remarkable", 
            "Superb", 
            "Impressive"
        };
    
    String[] uncompliments = {
            "Soooo badddddd T T", 
            "sorry, try again", 
            "Wrong!!", 
            "real???", 
            "Nahhh", 
            "Nice try bro, it's not", 
        };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField1 = new javax.swing.JTextField();
        txtField3 = new javax.swing.JTextField();
        txtField2 = new javax.swing.JTextField();
        lbNumber1 = new javax.swing.JLabel();
        lbNumber2 = new javax.swing.JLabel();
        lbNumber3 = new javax.swing.JLabel();
        btnRandom = new javax.swing.JToggleButton();
        txtFieldResult = new javax.swing.JTextField();
        txtField5 = new javax.swing.JTextField();
        btnCheckAns = new javax.swing.JToggleButton();
        btnTrulth = new javax.swing.JToggleButton();
        lbResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtField1.setColumns(10);

        txtField3.setColumns(10);

        txtField2.setColumns(10);
        txtField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField2ActionPerformed(evt);
            }
        });

        lbNumber1.setText("Number1");

        lbNumber2.setText("Number2");

        lbNumber3.setText("Number3");

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        txtFieldResult.setColumns(10);

        txtField5.setColumns(10);
        txtField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField5ActionPerformed(evt);
            }
        });

        btnCheckAns.setText("Check Ans");
        btnCheckAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnsActionPerformed(evt);
            }
        });

        btnTrulth.setText("Trulth");
        btnTrulth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrulthActionPerformed(evt);
            }
        });

        lbResult.setText("Result");

        jLabel2.setText("The truth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lbResult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckAns)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnTrulth))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumber1)
                            .addComponent(lbNumber3)
                            .addComponent(lbNumber2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRandom)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumber1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumber2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumber3))
                .addGap(18, 18, 18)
                .addComponent(btnRandom)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAns)
                    .addComponent(lbResult)
                    .addComponent(txtFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrulth)
                    .addComponent(txtField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField2ActionPerformed

    private void txtField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField5ActionPerformed

    private void btnCheckAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnsActionPerformed
        int ansToInt = Integer.parseInt(txtFieldResult.getText()); // คำตอบ User ที่เป็น int
        
        fact1ToInt = Integer.parseInt(txtField1.getText()); // textField1 Integer
        fact2ToInt = Integer.parseInt(txtField2.getText()); // textField2 Integer
        fact3ToInt = Integer.parseInt(txtField3.getText()); // // textField3 Integer
        
        
        realAnswer = fact1ToInt + fact2ToInt + fact3ToInt; // sum 3 textField
        
        if (realAnswer == ansToInt) {
            JOptionPane.showMessageDialog(null, compliments[rnd.nextInt(compliments.length)], "Message", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, uncompliments[rnd.nextInt(uncompliments.length)], "Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckAnsActionPerformed

    private void btnTrulthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrulthActionPerformed
        fact1ToInt = Integer.parseInt(txtField1.getText()); // textField1 Integer
        fact2ToInt = Integer.parseInt(txtField2.getText()); // textField2 Integer
        fact3ToInt = Integer.parseInt(txtField3.getText()); // // textField3 Integer
        
        realAnswer = fact1ToInt + fact2ToInt + fact3ToInt; // sum 3 textField
        
        txtField5.setText(realAnswer + "");
    }//GEN-LAST:event_btnTrulthActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        randomNum1 = rnd.nextInt(10) + 1;
        randomNum2 = rnd.nextInt(10) + 1;
        randomNum3 = rnd.nextInt(10) + 1;
        
        txtField1.setText(randomNum1 + "");
        txtField2.setText(randomNum2 + "");
        txtField3.setText(randomNum3 + "");
        
    }//GEN-LAST:event_btnRandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(randomSumOutput2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(randomSumOutput2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(randomSumOutput2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(randomSumOutput2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new randomSumOutput2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCheckAns;
    private javax.swing.JToggleButton btnRandom;
    private javax.swing.JToggleButton btnTrulth;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbNumber1;
    private javax.swing.JLabel lbNumber2;
    private javax.swing.JLabel lbNumber3;
    private javax.swing.JLabel lbResult;
    private javax.swing.JTextField txtField1;
    private javax.swing.JTextField txtField2;
    private javax.swing.JTextField txtField3;
    private javax.swing.JTextField txtField5;
    private javax.swing.JTextField txtFieldResult;
    // End of variables declaration//GEN-END:variables
}
